const unitTagData = {
  Koguro: { availability: ["Limited"], rarities: ["Vanguard", "Koguro"], elements: ["Nature"], aoes: ["Circle"], mechanics: ["Ability", "CC", "Buffer", "DOT", "Domain", "Nuke"] },
  Vsjw: { availability: ["Permanent"], rarities: ["Vanguard", "Vsjw"], elements: ["Unknown"], aoes: ["Circle"], mechanics: ["Ability", "Summoner", "Nuke", "Immune"] },
  Divalo: { availability: ["Unobtainable"], rarities: ["Vanguard", "Divalo"], elements: ["Cosmic"], aoes: ["Line"], mechanics: ["Ability", "Domain", "CC", "Immune"] },
  Rogita: { availability: ["Unobtainable"], rarities: ["Vanguard", "Rogita"], elements: ["Blast"], aoes: ["ACone"], mechanics: ["Ability", "CC"] },

  Conqueror: { availability: ["Limited"], rarities: ["Secret"], elements: ["Blast"], aoes: ["OCone"], mechanics: ["Ability", "CC"] },
  Slime: { availability: ["Limited"], rarities: ["Secret"], elements: ["Water"], aoes: ["Full"], mechanics: ["Ability"] },
  Astolfo: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Passion"], aoes: ["Full"], mechanics: ["Ability", "Buffer", "CC", "Debuffer"] },
  Byeken: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Unbound"], aoes: ["OCone"], mechanics: ["Ability", "CC", "Meter", "Debuffer"] },
  Lfelt: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Passion"], aoes: ["OCone"], mechanics: ["Ability", "CC", "Meter", "Nuke"] },
  SmithJohn: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Unknown", "Blast"], aoes: ["OCone"], mechanics: ["Ability", "Meter", "Nuke", "Immune"] },
  LordofShadows: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Blast"], aoes: ["Full"], mechanics: ["Ability", "Meter", "Nuke", "Immune"] },
  Clatakiri: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Water"], aoes: ["Full"], mechanics: ["CC"] },
  SuperVogito: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Holy"], aoes: ["Circle"], mechanics: ["Immune", "Debuffer"] },
  Roku: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Water"], aoes: ["OCone"], mechanics: ["Ability", "Nuke", "Meter", "CC"] },
  Vogita: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Blast"], aoes: ["Ocone"], mechanics: ["Ability", "Meter", "CC"] },
  KidBoo: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Cosmic"], aoes: ["Circle"], mechanics: ["Immune"] },
  Boohon: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Cosmic"], aoes: ["Circle"], mechanics: ["Immune", "Buffer", "Ability", "Summoner"] },
  ChoyJongEn: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Fire"], aoes: ["Line"], mechanics: ["Nuke", "DOT"] },
  Friran: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Nature"], aoes: ["ACone"], mechanics: ["Ability", "Summoner", "Immune"] },
  Eizan: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Unbound"], aoes: ["Full"], mechanics: ["Ability", "Immune", "CC", "Debuffer"] },
  Yehowach: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Cosmic"], aoes: ["Full"], mechanics: ["Ability", "Buffer", "Debuffer", "Immune"] },
  Yomomata: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Fire"], aoes: ["Full"], mechanics: ["DOT", "Ability", "Summoner"] },
  Sukono: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Curse", "Fire"], aoes: ["ACone"], mechanics: ["DOT", "Ability", "Immune", "Domain", "Debuffer", "Nuke"] },
  Gujo: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Cosmic"], aoes: ["Full"], mechanics: ["CC", "Immune", "Ability", "Domain"] },
  Alocard: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Unbound"], aoes: ["Full"], mechanics: ["Ability", "Summoner", "Debuffer", "DOT"] },
  Igros: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Curse"], aoes: ["Full"], mechanics: ["Immune"] },
  Regnaw: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Holy"], aoes: ["Circle"], mechanics: ["CC"] },
  Soburo: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Passion"], aoes: ["Circle"], mechanics: ["Ability", "Buffer"] },
  Isdead: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Passion"], aoes: ["Circle"], mechanics: ["Ability", "CC", "Buffer"] },
  Sokora: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Curse"], aoes: ["Full"], mechanics: ["Immune", "Ability", "Buffer"] },
  Salter: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Curse"], aoes: ["Circle"], mechanics: ["CC", "DOT", "Debuffer", "Immune"] },

  Arc: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Holy"], aoes: ["ACone"], mechanics: ["Ability", "CC", "Summoner", "DOT"] },
  Hebano: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Fire"], aoes: ["Circle"], mechanics: ["DOT", "Buffer", "Debuffer"] },
  Marlin: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Nature"], aoes: ["Circle"], mechanics: ["Ability", "Buffer", "Debuffer"] },
  Rudie: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["Full"], mechanics: ["Ability", "Meter", "Buffer", "Nuke"] },
  Al: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["OCone"], mechanics: ["Meter", "Buffer", "CC"] },
  DarkMage: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["OCone"], mechanics: ["Meter", "Debuffer", "CC", "DOT"] },
  Dawntay: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Unbound"], aoes: ["Circle", "Full"], mechanics: ["Meter"] },
  Vigil: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Spark"], aoes: ["OCone", "Full"], mechanics: ["Meter"] },
  Dave: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Spark"], aoes: ["OCone"], mechanics: [] },
  Luce: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Spark"], aoes: ["Full"], mechanics: ["Debuffer"] },
  Zion: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Fire"], aoes: ["Circle"], mechanics: ["DOT"] },
  Julias: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["Circle"], mechanics: ["CC"] },
  Tuji: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Unbound"], aoes: ["ACone"], mechanics: ["Ability"] },
  Renguko: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Fire"], aoes: ["Circle"], mechanics: ["DOT", "Debuffer"] },
  Okorun: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Curse"], aoes: ["Line"], mechanics: [] },
  Mimi: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Nature"], aoes: ["Acone"], mechanics: [] },
  Pweeny: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["Line"], mechanics: [] },
  Saiko: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Unbound"], aoes: ["Circle"], mechanics: ["DOT"] },
  Diogo: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Holy"], aoes: ["Circle"], mechanics: ["Ability", "CC", "Domain"] },
  Gilgamesh: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Holy", "Unbound"], aoes: ["Circle"], mechanics: ["Ability", "Nuke", "Immune"] },
  Emmie: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["Line"], mechanics: ["CC"] },
  Foboko: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Nature"], aoes: ["Circle"], mechanics: ["CC", "Buffer"] },
  Karem: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Fire"], aoes: ["Full"], mechanics: ["DOT", "CC"] },

  Ichiga: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Cosmic"], aoes: ["Circle"], mechanics: ["Ability", "Nuke"] },

  // { name: "Brisket", maxCost: 0, tags: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Spark"], aoes: ["Circle"], mechanics: ["Ability", "Meter"] } },
  // { name: "Gear Boy", maxCost: 0, tags: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Spark"], aoes: ["Circle"], mechanics: ["Ability", "Meter"] } },
  // { name: "Kazzy", maxCost: 0, tags: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Nature"], aoes: ["ACone"], mechanics: ["Ability", "CC", "Debuffer", "Meter"] } },
  // { name: "Rohan", maxCost: 0, tags: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Blast"], aoes: ["Splash"], mechanics: ["Immune"] } },
}