const unitTagData = {
  GujoFamiliar: { availability: ["Permanent"], rarities: ["Secret", "Gujo"], elements: ["Cosmic"], aoes: ["Full"], mechanics: ["CC", "Immune", "Ability", "Domain"] },
  SukonoFamiliar: { availability: ["Permanent"], rarities: ["Secret", "Sukono"], elements: ["Curse", "Fire"], aoes: ["ACone"], mechanics: ["DOT", "Ability", "Immune", "Domain", "Debuffer", "Nuke"] },
  TengonFamiliar: { availability: ["Permanent"], rarities: ["Mythic", "Tengon"], elements: ["Blast", "Fire"], aoes: ["Full"], mechanics: ["Debuffer", "Buffer"] },
  GilgameshFamiliar: { availability: ["Permanent"], rarities: ["Exclusive", "Gilgamesh"], elements: ["Holy", "Unbound"], aoes: ["ACone"], mechanics: ["Nuke", "CC", "Immune", "Ability"] },

  BrolziSuper: { availability: ["Permanent"], rarities: ["Vanguard", "BrolziSuper"], elements: ["Unbound"], aoes: ["OCone"], mechanics: ["Debuffer", "Buffer", "Ability", "Domain"] },
  RogitaSuper: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Blast"], aoes: ["Splash"], mechanics: ["Buffer", "Immune"] },
  LordFriezo: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Cosmic"], aoes: ["Circle"], mechanics: ["Summoner", "Immune"] },
  Wolf: { availability: ["Limited"], rarities: ["Secret"], elements: ["Spark"], aoes: ["OCone"], mechanics: ["CC"] },

  TheStruggler: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Unbound"], aoes: ["Full"], mechanics: ["Ability", "CC", "DOT"] },
  TheFalcon: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Cosmic"], aoes: ["OCone"], mechanics: ["Debuffer", "CC", "Buffer"] },
  TheKing: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Curse"], aoes: ["Full"], mechanics: [] },
  TheWitch: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Nature"], aoes: ["Full"], mechanics: ["Debuffer", "Buffer"] },
  TheSmith: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Fire"], aoes: ["Single"], mechanics: ["Buffer"] },
  
  Aurin: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Blast"], aoes: ["Single"], mechanics: ["Buffer"] },
  Orehimi: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Passion"], aoes: ["Single"], mechanics: ["Buffer"] },

  GoblinKiller: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Unbound"], aoes: ["Full"], mechanics: ["Debuffer"] },
  Priestess: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Holy"], aoes: ["Line"], mechanics: ["CC"] },

  GG: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Curse"], aoes: ["OCone"], mechanics: [] },

  Iscanur: { availability: ["Limited"], rarities: ["Vanguard", "Iscanur"], elements: ["Fire"], aoes: ["Circle"], mechanics: ["Ability", "CC", "Nuke"] },
  Koguro: { availability: ["Limited"], rarities: ["Vanguard", "Koguro"], elements: ["Nature"], aoes: ["Circle"], mechanics: ["Ability", "CC", "Buffer", "DOT", "Domain", "Nuke"] },
  Vsjw: { availability: ["Permanent"], rarities: ["Vanguard", "Vsjw"], elements: ["Unknown"], aoes: ["Circle"], mechanics: ["Ability", "Summoner", "Nuke", "Immune"] },
  Divalo: { availability: ["Unobtainable"], rarities: ["Vanguard", "Divalo"], elements: ["Cosmic"], aoes: ["Line"], mechanics: ["Ability", "Domain", "CC", "Immune"] },
  Rogita: { availability: ["Unobtainable"], rarities: ["Vanguard", "Rogita"], elements: ["Blast"], aoes: ["ACone"], mechanics: ["Ability", "CC"] },

  Leo: { availability: ["Limited"], rarities: ["Secret"], elements: ["Fire"], aoes: ["Full"], mechanics: ["DOT"] },
  MonkeyKing: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Holy"], aoes: ["Circle"], mechanics: ["Ability", "Buffer"] },
  GiantQueen: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Cosmic"], aoes: ["Full"], mechanics: ["Buffer"] },
  Arin: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Cosmic"], aoes: ["Full"], mechanics: ["Ability", "Buffer", "Nuke"] },
  Conqueror: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Blast"], aoes: ["OCone"], mechanics: ["Ability", "CC"] },
  Slime: { availability: ["Limited"], rarities: ["Secret"], elements: ["Water"], aoes: ["Full"], mechanics: ["Ability"] },
  Astolfo: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Passion"], aoes: ["Full"], mechanics: ["Ability", "Buffer", "CC", "Debuffer"] },
  Byeken: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Unbound"], aoes: ["OCone"], mechanics: ["Ability", "CC", "Meter", "Debuffer"] },
  Lfelt: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Passion"], aoes: ["OCone"], mechanics: ["Ability", "CC", "Meter", "Nuke"] },
  SmithJohn: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Unknown", "Blast"], aoes: ["OCone"], mechanics: ["Ability", "Meter", "Nuke", "Immune"] },
  LordofShadows: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Blast"], aoes: ["Full"], mechanics: ["Ability", "Meter", "Nuke"] },
  Clatakiri: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Water"], aoes: ["Full"], mechanics: ["CC"] },
  SuperVogito: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Holy"], aoes: ["Circle"], mechanics: ["Immune", "Debuffer"] },
  Roku: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Water"], aoes: ["OCone"], mechanics: ["Ability", "Nuke", "Meter", "CC"] },
  Vogita: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Blast"], aoes: ["Ocone"], mechanics: ["Ability", "Meter", "CC"] },
  KidBoo: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Cosmic"], aoes: ["Circle"], mechanics: ["Immune"] },
  Boohon: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Cosmic"], aoes: ["Circle"], mechanics: ["Immune", "Buffer", "Ability", "Summoner"] },
  ChoyJongEn: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Fire"], aoes: ["Line"], mechanics: ["Nuke", "DOT"] },
  Friran: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Nature"], aoes: ["ACone"], mechanics: ["Ability", "Summoner", "Immune"] },
  Eizan: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Unbound"], aoes: ["Full"], mechanics: ["Ability", "Immune", "CC", "Debuffer"] },
  Yehowach: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Cosmic"], aoes: ["Full"], mechanics: ["Ability", "Buffer", "Immune"] },
  Yomomata: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Fire"], aoes: ["Full"], mechanics: ["DOT", "Ability", "Summoner"] },
  Valentine: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Passion"], aoes: ["Circle"], mechanics: [""] },
  Sukono: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Curse", "Fire"], aoes: ["ACone"], mechanics: ["DOT", "Ability", "Immune", "Domain", "Debuffer", "Nuke"] },
  Gujo: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Cosmic"], aoes: ["Full"], mechanics: ["CC", "Immune", "Ability", "Domain"] },
  Alocard: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Unbound"], aoes: ["Full"], mechanics: ["Ability", "Summoner", "Debuffer", "DOT"] },
  Igros: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Curse"], aoes: ["Full"], mechanics: ["Immune"] },
  Regnaw: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Holy"], aoes: ["Circle"], mechanics: ["CC"] },
  Soburo: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Passion"], aoes: ["Circle"], mechanics: ["Ability", "Buffer"] },
  Isdead: { availability: ["Unobtainable"], rarities: ["Secret"], elements: ["Passion"], aoes: ["Circle"], mechanics: ["Ability", "CC", "Buffer"] },
  Sokora: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Unknown"], aoes: ["Full"], mechanics: ["Immune", "Ability", "Buffer"] },
  Salter: { availability: ["Permanent"], rarities: ["Secret"], elements: ["Curse"], aoes: ["Circle"], mechanics: ["CC", "DOT", "Debuffer", "Immune"] },

  Ali: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Fire"], aoes: ["OCone"], mechanics: ["DOT"] },
  Hei: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Curse"], aoes: ["Full"], mechanics: ["DOT"] },
  Newsman: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["OCone"], mechanics: ["CC", "Debuffer", "DOT"] },
  Quetzalcoatl: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Fire"], aoes: ["Full"], mechanics: ["DOT", "Buffer"] },
  Reimu: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Holy"], aoes: ["Full"], mechanics: ["Ability"] },
  Sakuya: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Nature"], aoes: ["Full"], mechanics: ["Ability", "Domain", "CC"] },
  Arc: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Holy"], aoes: ["ACone"], mechanics: ["Ability", "CC", "Summoner", "DOT"] },
  Hebano: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Fire"], aoes: ["Circle"], mechanics: ["DOT", "Buffer", "Debuffer"] },
  Marlin: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Nature"], aoes: ["Circle"], mechanics: ["Ability", "Buffer", "Debuffer"] },
  Rudie: { availability: ["Limited"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["Full"], mechanics: ["Ability", "Meter", "Buffer", "Nuke"] },
  Al: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["OCone"], mechanics: ["Meter", "Buffer", "CC"] },
  DarkMage: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Curse"], aoes: ["OCone"], mechanics: ["Meter", "Debuffer", "CC", "DOT"] },
  Dawntay: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Unbound"], aoes: ["Circle", "Full"], mechanics: ["Meter"] },
  Vigil: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Spark"], aoes: ["OCone", "Full"], mechanics: ["Meter"] },
  Dave: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Spark"], aoes: ["OCone"], mechanics: [] },
  Luce: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Spark"], aoes: ["Full"], mechanics: ["Debuffer"] },
  Sosora: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Passion"], aoes: ["OCone"], mechanics: ["DOT"] },
  Dodara: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Blast"], aoes: ["Circle"], mechanics: ["CC", "Nuke"] },
  Zion: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Fire"], aoes: ["Circle"], mechanics: ["DOT"] },
  Julias: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["Circle"], mechanics: ["CC"] },
  Tuji: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Unbound"], aoes: ["ACone"], mechanics: ["Ability"] },
  Renguko: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Fire"], aoes: ["Circle"], mechanics: ["DOT", "Debuffer"] },
  Okorun: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Curse"], aoes: ["Line"], mechanics: [] },
  Mimi: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Nature"], aoes: ["Acone"], mechanics: [] },
  Pweeny: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["Line"], mechanics: [] },
  Saiko: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Unbound"], aoes: ["Circle"], mechanics: ["DOT"] },
  Diogo: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Holy"], aoes: ["Circle"], mechanics: ["Ability", "CC", "Domain"] },
  Gilgamesh: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Holy", "Unbound"], aoes: ["Circle"], mechanics: ["Ability", "Nuke", "Immune"] },
  Emmie: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Water"], aoes: ["Line"], mechanics: ["CC"] },
  Foboko: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Nature"], aoes: ["Circle"], mechanics: ["CC", "Buffer"] },
  Karem: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Fire"], aoes: ["Full"], mechanics: ["DOT", "CC"] },
  RomandRan: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Curse"], aoes: ["Circle"], mechanics: ["Ability"] },
  HarukaRin: { availability: ["Unobtainable"], rarities: ["Exclusive"], elements: ["Passion"], aoes: ["Full"], mechanics: ["Buffer"] },

  Ken: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Blast"], aoes: ["Circle"], mechanics: ["CC", "DOT"] },
  Makoso: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Blast"], aoes: ["Circle"], mechanics: [] },
  Levy: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Unbound"], aoes: ["Circle"], mechanics: [] },
  Riner: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Curse"], aoes: ["Line"], mechanics: ["Buffer"] },
  Zak: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Curse"], aoes: ["OCone"], mechanics: ["Buffer", "Ability"] },
  Brisket: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Spark"], aoes: ["Circle"], mechanics: ["Ability", "Nuke", "Meter"] },
  GearBoy: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Spark"], aoes: ["Circle"], mechanics: ["Ability", "Meter"] },
  Kazzy: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Nature"], aoes: ["OCone"], mechanics: ["Ability", "CC", "Immune", "Debuffer", "Meter", "DOT"] },
  NotGoodGuy: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Fire"], aoes: ["OCone"], mechanics: ["Ability", "DOT", "Immune", "Meter"] },
  Deruta: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Nature"], aoes: ["Circle"], mechanics: [] },
  Hercool: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Nature"], aoes: ["Circle"], mechanics: ["Buffer"] },
  Rohan: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Blast"], aoes: ["Splash"], mechanics: ["Immune"] },
  Ichiga: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Cosmic"], aoes: ["Circle"], mechanics: ["Ability", "Nuke"] },
  Gazelle: { availability: ["Unobtainable"], rarities: ["Mythic"], elements: ["Passion"], aoes: ["Circle"], mechanics: ["Buffer"] },
  Kempache: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Unbound"], aoes: ["ACone"], mechanics: ["CC"] },
  Kiskae: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Nature"], aoes: ["Circle"], mechanics: ["DOT", "CC", "Debuffer"] },
  Oryo: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Water"], aoes: ["Circle"], mechanics: [] },
  Yuruicha: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Spark"], aoes: ["OCone"], mechanics: ["CC", "Immune"] },
  Lilia: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Unbound"], aoes: ["Circle"], mechanics: ["Ability", "Summoner"] },
  Ishtar: { availability: ["Unobtainable"], rarities: ["Mythic"], elements: ["Holy"], aoes: ["Circle"], mechanics: ["Ability", "Nuke", "Buffer"] },
  CuChulainn: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Unbound"], aoes: ["Circle"], mechanics: ["Debuffer"] },
  Archer: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Blast"], aoes: ["Circle"], mechanics: ["Ability", "Immune", "Debuffer"] },
  Saber: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Holy"], aoes: ["Circle"], mechanics: ["Ability", "CC", "Immune", "Nuke"] },
  Medea: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Curse"], aoes: ["Circle"], mechanics: ["Ability", "Debuffer"] },
  Medusa: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Passion"], aoes: ["OCone"], mechanics: ["Ability", "CC", "DOT"] },
  Johnni: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Blast"], aoes: ["Circle"], mechanics: ["Ability", "CC"] },
  Giro: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Nature"], aoes: ["Stadium"], mechanics: [] },
  Chaso: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Unbound"], aoes: ["Full"], mechanics: ["DOT"] },
  Jago: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Fire"], aoes: ["Circle"], mechanics: ["Ability", "DOT", "Domain"] },
  Todu: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Passion"], aoes: ["Circle"], mechanics: ["Ability"] },
  Akazo: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Water"], aoes: ["Stadium"], mechanics: ["Ability", "Immune"] },
  Tengon: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Blast"], aoes: ["Full"], mechanics: ["Immune"] },
  ChaIn: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Holy"], aoes: ["OCone"], mechanics: ["Immune"] },
  Noruto: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Unbound"], aoes: ["Circle"], mechanics: [] },
  Obita: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Nature"], aoes: ["OCone"], mechanics: ["DOT"] },
  SongJinwu: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Curse"], aoes: ["Circle"], mechanics: ["Ability", "Summoner"] },
  Sosuke: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Spark"], aoes: ["Circle"], mechanics: ["CC"] },
  VogitaSuper: { availability: ["Permanent"], rarities: ["Mythic"], elements: ["Blast"], aoes: ["Circle"], mechanics: [] },
}